name: Build Base image

on:
  push:
    paths:
      - '.github/workflows/build-base-container.yml'
      - 'Dockerfile.base'

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: c2sm
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: false
          tags: c2sm/extpar-base:latest
          platforms: linux/amd64
